import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 9, color: '#1a1a1a', lineHeight: 1.4 },
  header: { marginBottom: 20, borderBottom: '2px solid #3b82f6', paddingBottom: 10 },
  title: { fontSize: 20, fontFamily: 'Helvetica-Bold', color: '#111827', marginBottom: 4 },
  subtitle: { fontSize: 9, color: '#6b7280', textTransform: 'uppercase' },
  
  metaGrid: { flexDirection: 'row', gap: 20, marginBottom: 20, padding: 10, backgroundColor: '#f9fafb', borderRadius: 8 },
  metaItem: { flex: 1 },
  metaLabel: { fontSize: 7, color: '#9ca3af', textTransform: 'uppercase', marginBottom: 2 },
  metaValue: { fontSize: 10, fontFamily: 'Helvetica-Bold' },
  
  sectionTitle: { fontSize: 12, fontFamily: 'Helvetica-Bold', color: '#3b82f6', marginTop: 15, marginBottom: 8, textTransform: 'uppercase', borderBottom: '1px solid #e5e7eb', paddingBottom: 4 },
  
  qaItem: { marginBottom: 15, padding: 10, backgroundColor: '#ffffff', border: '0.5px solid #f3f4f6', borderRadius: 6 },
  question: { fontSize: 9, fontFamily: 'Helvetica-Bold', color: '#1f2937', marginBottom: 4 },
  answer: { fontSize: 9, color: '#4b5563', marginBottom: 6, fontStyle: 'italic' },
  
  scoreRow: { flexDirection: 'row', gap: 15, marginTop: 4 },
  scoreBadge: { fontSize: 7, color: '#3b82f6', backgroundColor: '#eff6ff', padding: '2px 6px', borderRadius: 4 },
  
  feedback: { fontSize: 8, color: '#059669', marginTop: 4, paddingLeft: 8, borderLeft: '2px solid #10b981' },
  
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, borderTop: '0.5px solid #e5e7eb', paddingTop: 10, textAlign: 'center' },
  footerText: { fontSize: 7, color: '#9ca3af' }
});

interface SessionPDFProps {
  session: any;
  userName: string;
}

export const SessionPDF: React.FC<SessionPDFProps> = ({ session, userName }) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Interview Session Transcript</Text>
          <Text style={styles.subtitle}>Verified Neural Audit | {session.target_role}</Text>
        </View>

        {/* Metadata */}
        <View style={styles.metaGrid}>
          <View style={styles.metaItem}>
            <Text style={styles.metaLabel}>Candidate</Text>
            <Text style={styles.metaValue}>{userName}</Text>
          </View>
          <View style={styles.metaItem}>
            <Text style={styles.metaLabel}>Date</Text>
            <Text style={styles.metaValue}>{session.date}</Text>
          </View>
          <View style={styles.metaItem}>
            <Text style={styles.metaLabel}>Duration</Text>
            <Text style={styles.metaValue}>{session.duration_minutes} Minutes</Text>
          </View>
          <View style={styles.metaItem}>
            <Text style={styles.metaLabel}>Overall Score</Text>
            <Text style={styles.metaValue}>{session.interview_score}/100</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Complete Q&A Transcript</Text>

        {session.questions_and_answers?.map((qa: any, i: number) => (
          <View key={i} style={styles.qaItem} wrap={false}>
            <Text style={styles.question}>Q{i+1}: {qa.question}</Text>
            <Text style={styles.answer}>Candidate: "{qa.answer_transcript}"</Text>
            
            <View style={styles.scoreRow}>
               <Text style={styles.scoreBadge}>Latency: {qa.response_time_seconds}s</Text>
               {qa.scores && (
                 <>
                   <Text style={styles.scoreBadge}>Relevance: {qa.scores.relevance}/10</Text>
                   <Text style={styles.scoreBadge}>Technical: {qa.scores.technical}/10</Text>
                 </>
               )}
            </View>

            {qa.ai_feedback && (
              <Text style={styles.feedback}>AI Insight: {qa.ai_feedback}</Text>
            )}
          </View>
        ))}

        <Text style={styles.footer}>
           <Text style={styles.footerText}>Generated by Mocky AI Neural Link | {session.id} | Page 1</Text>
        </Text>
      </Page>
    </Document>
  );
};

export default SessionPDF;
